# Generated by Django 4.0.3 on 2022-05-05 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2083, verbose_name='プロジェクトURL')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('published_at', models.DateField(verbose_name='公開日')),
                ('updated_at', models.DateField(verbose_name='更新日')),
                ('number_of_session', models.PositiveIntegerField(default=0, verbose_name='流入数')),
                ('cvr', models.FloatField(default=0.0, verbose_name='CVR')),
                ('cv', models.PositiveIntegerField(default=0, verbose_name='CV数')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_articles', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('person_in_charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_in_charge', to=settings.AUTH_USER_MODEL, verbose_name='担当')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='プロジェクト')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(verbose_name='キーワード')),
                ('volume', models.PositiveIntegerField(default=0, verbose_name='検索数')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='記事')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.PositiveIntegerField(default=0, verbose_name='キーワード数')),
                ('ranking_page', models.CharField(max_length=2083, null=True, verbose_name='ランクインページ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日付')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.keyword', verbose_name='キーワード')),
            ],
        ),
    ]
