# Generated by Django 4.0.3 on 2022-05-31 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='プロジェクト名')),
                ('url', models.CharField(max_length=2083, verbose_name='プロジェクトURL')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
        ),
        migrations.CreateModel(
            name='Regex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.CharField(max_length=100, verbose_name='正規表現')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name_plural': 'Regex',
            },
        ),
        migrations.CreateModel(
            name='Weekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_week', models.PositiveIntegerField(default=0, verbose_name='年週')),
                ('session', models.PositiveIntegerField(default=0, verbose_name='流入数')),
                ('conversion', models.FloatField(default=0, verbose_name='CV数')),
                ('conversion_rate', models.FloatField(default=0.0, verbose_name='CVR')),
                ('page_view', models.FloatField(default=0, verbose_name='PV')),
                ('page_view_per_session', models.FloatField(default=0, verbose_name='PV/流入数')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='プロジェクト')),
                ('regex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.regex', verbose_name='正規表現')),
            ],
            options={
                'verbose_name_plural': 'Weekly',
            },
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.PositiveIntegerField(default=0, verbose_name='年月')),
                ('session', models.PositiveIntegerField(default=0, verbose_name='流入数')),
                ('conversion', models.FloatField(default=0, verbose_name='CV数')),
                ('conversion_rate', models.FloatField(default=0.0, verbose_name='CVR')),
                ('page_view', models.FloatField(default=0, verbose_name='PV')),
                ('page_view_per_session', models.FloatField(default=0, verbose_name='PV/流入数')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='プロジェクト')),
                ('regex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.regex', verbose_name='正規表現')),
            ],
            options={
                'verbose_name_plural': 'Monthly',
            },
        ),
    ]
