from django.db import models

from projects.models import Website, Keyword


class GetOrNoneManager(models.Manager):
    def get_or_none(self, **kwargs):
        try:
            return self.get(**kwargs)
        except self.model.DoesNotExist:
            return None


class KeywordSerp(models.Model):
    keyword = models.ForeignKey(
        Keyword,
        verbose_name='キーワード',
        on_delete=models.CASCADE
    ) 
    url_1 = models.CharField('1位', max_length=2083, blank=True, null=True)
    url_2 = models.CharField('2位', max_length=2083, blank=True, null=True)
    url_3 = models.CharField('3位', max_length=2083, blank=True, null=True)
    url_4 = models.CharField('4位', max_length=2083, blank=True, null=True)
    url_5 = models.CharField('5位', max_length=2083, blank=True, null=True)
    url_6 = models.CharField('6位', max_length=2083, blank=True, null=True)
    url_7 = models.CharField('7位', max_length=2083, blank=True, null=True)
    url_8 = models.CharField('8位', max_length=2083, blank=True, null=True)
    url_9 = models.CharField('9位', max_length=2083, blank=True, null=True)
    url_10 = models.CharField('10位', max_length=2083, blank=True, null=True)
    url_11 = models.CharField('11位', max_length=2083, blank=True, null=True)
    url_12 = models.CharField('12位', max_length=2083, blank=True, null=True)
    url_13 = models.CharField('13位', max_length=2083, blank=True, null=True)
    url_14 = models.CharField('14位', max_length=2083, blank=True, null=True)
    url_15 = models.CharField('15位', max_length=2083, blank=True, null=True)
    url_16 = models.CharField('16位', max_length=2083, blank=True, null=True)
    url_17 = models.CharField('17位', max_length=2083, blank=True, null=True)
    url_18 = models.CharField('18位', max_length=2083, blank=True, null=True)
    url_19 = models.CharField('19位', max_length=2083, blank=True, null=True)
    url_20 = models.CharField('20位', max_length=2083, blank=True, null=True)
    url_21 = models.CharField('21位', max_length=2083, blank=True, null=True)
    url_22 = models.CharField('22位', max_length=2083, blank=True, null=True)
    url_23 = models.CharField('23位', max_length=2083, blank=True, null=True)
    url_24 = models.CharField('24位', max_length=2083, blank=True, null=True)
    url_25 = models.CharField('25位', max_length=2083, blank=True, null=True)
    url_26 = models.CharField('26位', max_length=2083, blank=True, null=True)
    url_27 = models.CharField('27位', max_length=2083, blank=True, null=True)
    url_28 = models.CharField('28位', max_length=2083, blank=True, null=True)
    url_29 = models.CharField('29位', max_length=2083, blank=True, null=True)
    url_30 = models.CharField('30位', max_length=2083, blank=True, null=True)
    url_31 = models.CharField('31位', max_length=2083, blank=True, null=True)
    url_32 = models.CharField('32位', max_length=2083, blank=True, null=True)
    url_33 = models.CharField('33位', max_length=2083, blank=True, null=True)
    url_34 = models.CharField('34位', max_length=2083, blank=True, null=True)
    url_35 = models.CharField('35位', max_length=2083, blank=True, null=True)
    url_36 = models.CharField('36位', max_length=2083, blank=True, null=True)
    url_37 = models.CharField('37位', max_length=2083, blank=True, null=True)
    url_38 = models.CharField('38位', max_length=2083, blank=True, null=True)
    url_39 = models.CharField('39位', max_length=2083, blank=True, null=True)
    url_40 = models.CharField('40位', max_length=2083, blank=True, null=True)
    url_41 = models.CharField('41位', max_length=2083, blank=True, null=True)
    url_42 = models.CharField('42位', max_length=2083, blank=True, null=True)
    url_43 = models.CharField('43位', max_length=2083, blank=True, null=True)
    url_44 = models.CharField('44位', max_length=2083, blank=True, null=True)
    url_45 = models.CharField('45位', max_length=2083, blank=True, null=True)
    url_46 = models.CharField('46位', max_length=2083, blank=True, null=True)
    url_47 = models.CharField('47位', max_length=2083, blank=True, null=True)
    url_48 = models.CharField('48位', max_length=2083, blank=True, null=True)
    url_49 = models.CharField('49位', max_length=2083, blank=True, null=True)
    url_50 = models.CharField('50位', max_length=2083, blank=True, null=True)
    url_51 = models.CharField('51位', max_length=2083, blank=True, null=True)
    url_52 = models.CharField('52位', max_length=2083, blank=True, null=True)
    url_53 = models.CharField('53位', max_length=2083, blank=True, null=True)
    url_54 = models.CharField('54位', max_length=2083, blank=True, null=True)
    url_55 = models.CharField('55位', max_length=2083, blank=True, null=True)
    url_56 = models.CharField('56位', max_length=2083, blank=True, null=True)
    url_57 = models.CharField('57位', max_length=2083, blank=True, null=True)
    url_58 = models.CharField('58位', max_length=2083, blank=True, null=True)
    url_59 = models.CharField('59位', max_length=2083, blank=True, null=True)
    url_60 = models.CharField('60位', max_length=2083, blank=True, null=True)
    url_61 = models.CharField('61位', max_length=2083, blank=True, null=True)
    url_62 = models.CharField('62位', max_length=2083, blank=True, null=True)
    url_63 = models.CharField('63位', max_length=2083, blank=True, null=True)
    url_64 = models.CharField('64位', max_length=2083, blank=True, null=True)
    url_65 = models.CharField('65位', max_length=2083, blank=True, null=True)
    url_66 = models.CharField('66位', max_length=2083, blank=True, null=True)
    url_67 = models.CharField('67位', max_length=2083, blank=True, null=True)
    url_68 = models.CharField('68位', max_length=2083, blank=True, null=True)
    url_69 = models.CharField('69位', max_length=2083, blank=True, null=True)
    url_70 = models.CharField('70位', max_length=2083, blank=True, null=True)
    url_71 = models.CharField('71位', max_length=2083, blank=True, null=True)
    url_72 = models.CharField('72位', max_length=2083, blank=True, null=True)
    url_73 = models.CharField('73位', max_length=2083, blank=True, null=True)
    url_74 = models.CharField('74位', max_length=2083, blank=True, null=True)
    url_75 = models.CharField('75位', max_length=2083, blank=True, null=True)
    url_76 = models.CharField('76位', max_length=2083, blank=True, null=True)
    url_77 = models.CharField('77位', max_length=2083, blank=True, null=True)
    url_78 = models.CharField('78位', max_length=2083, blank=True, null=True)
    url_79 = models.CharField('79位', max_length=2083, blank=True, null=True)
    url_80 = models.CharField('80位', max_length=2083, blank=True, null=True)
    url_81 = models.CharField('81位', max_length=2083, blank=True, null=True)
    url_82 = models.CharField('82位', max_length=2083, blank=True, null=True)
    url_83 = models.CharField('83位', max_length=2083, blank=True, null=True)
    url_84 = models.CharField('84位', max_length=2083, blank=True, null=True)
    url_85 = models.CharField('85位', max_length=2083, blank=True, null=True)
    url_86 = models.CharField('86位', max_length=2083, blank=True, null=True)
    url_87 = models.CharField('87位', max_length=2083, blank=True, null=True)
    url_88 = models.CharField('88位', max_length=2083, blank=True, null=True)
    url_89 = models.CharField('89位', max_length=2083, blank=True, null=True)
    url_90 = models.CharField('90位', max_length=2083, blank=True, null=True)
    url_91 = models.CharField('91位', max_length=2083, blank=True, null=True)
    url_92 = models.CharField('92位', max_length=2083, blank=True, null=True)
    url_93 = models.CharField('93位', max_length=2083, blank=True, null=True)
    url_94 = models.CharField('94位', max_length=2083, blank=True, null=True)
    url_95 = models.CharField('95位', max_length=2083, blank=True, null=True)
    url_96 = models.CharField('96位', max_length=2083, blank=True, null=True)
    url_97 = models.CharField('97位', max_length=2083, blank=True, null=True)
    url_98 = models.CharField('98位', max_length=2083, blank=True, null=True)
    url_99 = models.CharField('99位', max_length=2083, blank=True, null=True)
    url_100 = models.CharField('100位', max_length=2083, blank=True, null=True)
    title_1 = models.TextField('タイトル1位', blank=True, null=True)
    title_2 = models.TextField('タイトル2位', blank=True, null=True)
    title_3 = models.TextField('タイトル3位', blank=True, null=True)
    title_4 = models.TextField('タイトル4位', blank=True, null=True)
    title_5 = models.TextField('タイトル5位', blank=True, null=True)
    title_6 = models.TextField('タイトル6位', blank=True, null=True)
    title_7 = models.TextField('タイトル7位', blank=True, null=True)
    title_8 = models.TextField('タイトル8位', blank=True, null=True)
    title_9 = models.TextField('タイトル9位', blank=True, null=True)
    title_10 = models.TextField('タイトル10位', blank=True, null=True)
    title_11 = models.TextField('タイトル11位', blank=True, null=True)
    title_12 = models.TextField('タイトル12位', blank=True, null=True)
    title_13 = models.TextField('タイトル13位', blank=True, null=True)
    title_14 = models.TextField('タイトル14位', blank=True, null=True)
    title_15 = models.TextField('タイトル15位', blank=True, null=True)
    title_16 = models.TextField('タイトル16位', blank=True, null=True)
    title_17 = models.TextField('タイトル17位', blank=True, null=True)
    title_18 = models.TextField('タイトル18位', blank=True, null=True)
    title_19 = models.TextField('タイトル19位', blank=True, null=True)
    title_20 = models.TextField('タイトル20位', blank=True, null=True)
    title_21 = models.TextField('タイトル21位', blank=True, null=True)
    title_22 = models.TextField('タイトル22位', blank=True, null=True)
    title_23 = models.TextField('タイトル23位', blank=True, null=True)
    title_24 = models.TextField('タイトル24位', blank=True, null=True)
    title_25 = models.TextField('タイトル25位', blank=True, null=True)
    title_26 = models.TextField('タイトル26位', blank=True, null=True)
    title_27 = models.TextField('タイトル27位', blank=True, null=True)
    title_28 = models.TextField('タイトル28位', blank=True, null=True)
    title_29 = models.TextField('タイトル29位', blank=True, null=True)
    title_30 = models.TextField('タイトル30位', blank=True, null=True)
    title_31 = models.TextField('タイトル31位', blank=True, null=True)
    title_32 = models.TextField('タイトル32位', blank=True, null=True)
    title_33 = models.TextField('タイトル33位', blank=True, null=True)
    title_34 = models.TextField('タイトル34位', blank=True, null=True)
    title_35 = models.TextField('タイトル35位', blank=True, null=True)
    title_36 = models.TextField('タイトル36位', blank=True, null=True)
    title_37 = models.TextField('タイトル37位', blank=True, null=True)
    title_38 = models.TextField('タイトル38位', blank=True, null=True)
    title_39 = models.TextField('タイトル39位', blank=True, null=True)
    title_40 = models.TextField('タイトル40位', blank=True, null=True)
    title_41 = models.TextField('タイトル41位', blank=True, null=True)
    title_42 = models.TextField('タイトル42位', blank=True, null=True)
    title_43 = models.TextField('タイトル43位', blank=True, null=True)
    title_44 = models.TextField('タイトル44位', blank=True, null=True)
    title_45 = models.TextField('タイトル45位', blank=True, null=True)
    title_46 = models.TextField('タイトル46位', blank=True, null=True)
    title_47 = models.TextField('タイトル47位', blank=True, null=True)
    title_48 = models.TextField('タイトル48位', blank=True, null=True)
    title_49 = models.TextField('タイトル49位', blank=True, null=True)
    title_50 = models.TextField('タイトル50位', blank=True, null=True)
    title_51 = models.TextField('タイトル51位', blank=True, null=True)
    title_52 = models.TextField('タイトル52位', blank=True, null=True)
    title_53 = models.TextField('タイトル53位', blank=True, null=True)
    title_54 = models.TextField('タイトル54位', blank=True, null=True)
    title_55 = models.TextField('タイトル55位', blank=True, null=True)
    title_56 = models.TextField('タイトル56位', blank=True, null=True)
    title_57 = models.TextField('タイトル57位', blank=True, null=True)
    title_58 = models.TextField('タイトル58位', blank=True, null=True)
    title_59 = models.TextField('タイトル59位', blank=True, null=True)
    title_60 = models.TextField('タイトル60位', blank=True, null=True)
    title_61 = models.TextField('タイトル61位', blank=True, null=True)
    title_62 = models.TextField('タイトル62位', blank=True, null=True)
    title_63 = models.TextField('タイトル63位', blank=True, null=True)
    title_64 = models.TextField('タイトル64位', blank=True, null=True)
    title_65 = models.TextField('タイトル65位', blank=True, null=True)
    title_66 = models.TextField('タイトル66位', blank=True, null=True)
    title_67 = models.TextField('タイトル67位', blank=True, null=True)
    title_68 = models.TextField('タイトル68位', blank=True, null=True)
    title_69 = models.TextField('タイトル69位', blank=True, null=True)
    title_70 = models.TextField('タイトル70位', blank=True, null=True)
    title_71 = models.TextField('タイトル71位', blank=True, null=True)
    title_72 = models.TextField('タイトル72位', blank=True, null=True)
    title_73 = models.TextField('タイトル73位', blank=True, null=True)
    title_74 = models.TextField('タイトル74位', blank=True, null=True)
    title_75 = models.TextField('タイトル75位', blank=True, null=True)
    title_76 = models.TextField('タイトル76位', blank=True, null=True)
    title_77 = models.TextField('タイトル77位', blank=True, null=True)
    title_78 = models.TextField('タイトル78位', blank=True, null=True)
    title_79 = models.TextField('タイトル79位', blank=True, null=True)
    title_80 = models.TextField('タイトル80位', blank=True, null=True)
    title_81 = models.TextField('タイトル81位', blank=True, null=True)
    title_82 = models.TextField('タイトル82位', blank=True, null=True)
    title_83 = models.TextField('タイトル83位', blank=True, null=True)
    title_84 = models.TextField('タイトル84位', blank=True, null=True)
    title_85 = models.TextField('タイトル85位', blank=True, null=True)
    title_86 = models.TextField('タイトル86位', blank=True, null=True)
    title_87 = models.TextField('タイトル87位', blank=True, null=True)
    title_88 = models.TextField('タイトル88位', blank=True, null=True)
    title_89 = models.TextField('タイトル89位', blank=True, null=True)
    title_90 = models.TextField('タイトル90位', blank=True, null=True)
    title_91 = models.TextField('タイトル91位', blank=True, null=True)
    title_92 = models.TextField('タイトル92位', blank=True, null=True)
    title_93 = models.TextField('タイトル93位', blank=True, null=True)
    title_94 = models.TextField('タイトル94位', blank=True, null=True)
    title_95 = models.TextField('タイトル95位', blank=True, null=True)
    title_96 = models.TextField('タイトル96位', blank=True, null=True)
    title_97 = models.TextField('タイトル97位', blank=True, null=True)
    title_98 = models.TextField('タイトル98位', blank=True, null=True)
    title_99 = models.TextField('タイトル99位', blank=True, null=True)
    title_100 = models.TextField('タイトル100位', blank=True, null=True)
    created_at = models.DateTimeField('登録日', auto_now_add=True)
 
    def __str__(self):
        return f'<Keyword: {self.keyword.keyword} | {self.created_at}>'


class Ranking(models.Model):
    website = models.ForeignKey(
        Website,
        verbose_name='サイト',
        on_delete=models.CASCADE
    )
    keyword = models.ForeignKey(
        Keyword,
        verbose_name='キーワード',
        on_delete=models.CASCADE
    )
    date = models.DateField('日付')
    ranking = models.PositiveIntegerField('順位', default=0)
    ranking_page = models.CharField('ランクインページ', max_length=2083, null=True, blank=True)
    title_link = models.TextField('タイトルリンク', null=True, blank=True)
    objects = GetOrNoneManager()

    class Meta:
        verbose_name_plural = 'Ranking'
        constraints = [
            models.UniqueConstraint(
                fields=['website', 'keyword', 'date'],
                name="ranking_unique"
            ),
        ]

    def __str__(self):
        return f'<Ranking: {self.website.domain} | {self.keyword.keyword} | {self.ranking} | {self.date}>'